package com.smartverse.churchlitebackend.service.memberportal;
import com.smartverse.churchlitebackend.config.context.RequestUserContext;import com.smartverse.churchlitebackend.controller.memberportal.MemberFinancialApprovalModels.*;import com.smartverse.churchlitebackend_gen.authorization.exception.ServiceException;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.LocalDateTime;import java.util.*;
@Service public class MemberFinancialApprovalService {private final JdbcTemplate jdbc;public MemberFinancialApprovalService(JdbcTemplate jdbc){this.jdbc=jdbc;}
 @Transactional(readOnly=true) public List<CashClosing> availableClosings(){return jdbc.query("select ct.id,c.description,ct.start_date,ct.end_date,ct.final_balance from cash_transactions ct join cash c on c.id=ct.cash where ct.end_date is not null order by ct.end_date desc",(r,n)->new CashClosing(r.getObject(1,UUID.class),r.getString(2),r.getObject(3,java.time.LocalDate.class),r.getObject(4,java.time.LocalDate.class),r.getDouble(5)));}
 @Transactional public Statement save(SaveRequest q){if(q==null||q.title()==null||q.title().isBlank()||q.cashClosingIds()==null||q.cashClosingIds().isEmpty())bad();UUID id=q.id()==null?UUID.randomUUID():q.id();if(q.id()==null)jdbc.update("insert into member_financial_statement(id,title,description,status,anonymous_salt) values(?,?,?,'DRAFT',?)",id,q.title().trim(),q.description(),UUID.randomUUID());else{if(jdbc.update("update member_financial_statement set title=?,description=? where id=? and status='DRAFT'",q.title().trim(),q.description(),id)==0)bad();jdbc.update("delete from member_financial_statement_cash where statement_id=?",id);}for(UUID cash:q.cashClosingIds()){if(jdbc.update("insert into member_financial_statement_cash(statement_id,cash_transaction_id) select ?,id from cash_transactions where id=? and end_date is not null",id,cash)==0)bad();}return one(id,null);}
 @Transactional public Statement publish(UUID id){if(!enabled())throw new ServiceException(HttpStatus.CONFLICT,"member_financial_approval_disabled");if(jdbc.update("update member_financial_statement set status='OPEN',published_at=? where id=? and status='DRAFT'",LocalDateTime.now(),id)==0)bad();return one(id,null);}
 @Transactional public Statement close(UUID id){if(jdbc.update("update member_financial_statement set status='CLOSED',closed_at=? where id=? and status='OPEN'",LocalDateTime.now(),id)==0)bad();return one(id,null);}
 @Transactional(readOnly=true) public List<Statement> adminList(){return ids("select id from member_financial_statement order by coalesce(published_at,closed_at) desc nulls last,title",null);}
 @Transactional(readOnly=true) public List<Statement> memberList(){if(!enabled())return List.of();UUID user=RequestUserContext.getRequired();return ids("select id from member_financial_statement where status in ('OPEN','CLOSED') order by published_at desc",user);}
 @Transactional public Statement vote(UUID id,VoteRequest q){if(!enabled())throw new ServiceException(HttpStatus.CONFLICT,"member_financial_approval_disabled");UUID user=RequestUserContext.getRequired();String fingerprint=fingerprint(id,user);try{int inserted=jdbc.update("insert into member_financial_statement_vote(id,statement_id,voter_fingerprint,approved) select ?,id,?,? from member_financial_statement where id=? and status='OPEN'",UUID.randomUUID(),fingerprint,q.approved(),id);if(inserted==0)bad();}catch(org.springframework.dao.DuplicateKeyException e){throw new ServiceException(HttpStatus.CONFLICT,"member_financial_approval_already_voted");}return one(id,user);}
 private List<Statement> ids(String sql,UUID user){return jdbc.query(sql,(r,n)->r.getObject(1,UUID.class)).stream().map(id->one(id,user)).toList();}
 private Statement one(UUID id,UUID user){var base=jdbc.query("select id,title,description,status,published_at,closed_at,anonymous_salt from member_financial_statement where id=?",(r,n)->new Object[]{r.getObject(1,UUID.class),r.getString(2),r.getString(3),r.getString(4),r.getObject(5,LocalDateTime.class),r.getObject(6,LocalDateTime.class),r.getObject(7,UUID.class)},id);if(base.isEmpty())throw new ServiceException(HttpStatus.NOT_FOUND,"member_financial_statement_not_found");Object[] b=base.getFirst();var closings=jdbc.query("select ct.id,c.description,ct.start_date,ct.end_date,ct.final_balance from member_financial_statement_cash s join cash_transactions ct on ct.id=s.cash_transaction_id join cash c on c.id=ct.cash where s.statement_id=? order by ct.end_date",(r,n)->new CashClosing(r.getObject(1,UUID.class),r.getString(2),r.getObject(3,java.time.LocalDate.class),r.getObject(4,java.time.LocalDate.class),r.getDouble(5)),id);var totals=jdbc.queryForMap("select coalesce(sum(case when f.type_financial=0 then t.value else 0 end),0) revenue,coalesce(sum(case when f.type_financial=1 then t.value else 0 end),0) expense from member_financial_statement_cash s join transactions t on t.cash_transaction=s.cash_transaction_id join financial f on f.id=t.financial where s.statement_id=?",id);var votes=jdbc.queryForMap("select count(*) filter(where approved) approvals,count(*) filter(where not approved) rejections,count(*) votes from member_financial_statement_vote where statement_id=?",id);long a=((Number)votes.get("approvals")).longValue(),v=((Number)votes.get("votes")).longValue();boolean voted=user!=null&&Boolean.TRUE.equals(jdbc.queryForObject("select exists(select 1 from member_financial_statement_vote where statement_id=? and voter_fingerprint=?)",Boolean.class,id,fingerprint(id,user)));return new Statement((UUID)b[0],(String)b[1],(String)b[2],(String)b[3],(LocalDateTime)b[4],(LocalDateTime)b[5],closings,((Number)totals.get("revenue")).doubleValue(),((Number)totals.get("expense")).doubleValue(),a,((Number)votes.get("rejections")).longValue(),v,v==0?0:a*100d/v,voted);}
 private boolean enabled(){return Boolean.TRUE.equals(jdbc.queryForObject("select member_approval_enabled from member_portal_transparency_configuration where id=true",Boolean.class));}
 private String fingerprint(UUID statement,UUID user){UUID salt=jdbc.queryForObject("select anonymous_salt from member_financial_statement where id=?",UUID.class,statement);try{byte[] hash=MessageDigest.getInstance("SHA-256").digest((statement+":"+user+":"+salt).getBytes(StandardCharsets.UTF_8));return java.util.HexFormat.of().formatHex(hash);}catch(Exception e){throw new IllegalStateException(e);}}
 private void bad(){throw new ServiceException(HttpStatus.BAD_REQUEST,"member_financial_statement_invalid");}
}
