server.port=${SERVER_PORT}
server.servlet.context-path=/${SERVICE_NAME}

spring.main.allow-bean-definition-overriding=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

flyway.ignoreMissingMigrations=true


app.frontend.base-url=${FRONTEND_BASE_URL:http://localhost:4200/church-lite}
resend.api-key=${RESEND_KEY:}
resend.from=${RESEND_FROM:Church Lite <no-reply@smartverse.com.br>}
#rabbit.exchange.name=router.api
#rabbit.routingKey.name=router.product-inbox
#rabbit.queue.name=product.queue
