-- Keep database enum columns aligned with the ordinal mapping generated by JPA.
-- The CASE expressions support databases containing either enum names or numeric text.

ALTER TABLE person
    ALTER COLUMN status TYPE integer
        USING CASE upper(status::text)
            WHEN 'ACTIVE' THEN 0
            WHEN 'INACTIVE' THEN 1
            ELSE status::text::integer
        END,
    ALTER COLUMN gender TYPE integer
        USING CASE upper(gender::text)
            WHEN 'MALE' THEN 0
            WHEN 'FEMALE' THEN 1
            ELSE gender::text::integer
        END,
    ALTER COLUMN marital_status TYPE integer
        USING CASE upper(marital_status::text)
            WHEN 'SINGLE' THEN 0
            WHEN 'MARRIED' THEN 1
            WHEN 'DIVORCED' THEN 2
            WHEN 'WIDOWED' THEN 3
            WHEN 'SEPARATED' THEN 4
            WHEN 'CIVIL_UNION' THEN 5
            ELSE marital_status::text::integer
        END;

ALTER TABLE person_docs
    ALTER COLUMN type_person TYPE integer
        USING CASE upper(type_person::text)
            WHEN 'NATURAL_PERSON' THEN 0
            WHEN 'LEGAL_PERSON' THEN 1
            ELSE type_person::text::integer
        END;

ALTER TABLE plan_account
    ALTER COLUMN type TYPE integer
        USING CASE upper(type::text)
            WHEN 'ANALYTICAL' THEN 0
            WHEN 'SYNTHETIC' THEN 1
            ELSE type::text::integer
        END;

ALTER TABLE cash
    ALTER COLUMN type_cash TYPE integer
        USING CASE upper(type_cash::text)
            WHEN 'CASH' THEN 0
            WHEN 'BANK' THEN 1
            ELSE type_cash::text::integer
        END,
    ALTER COLUMN status TYPE integer
        USING CASE upper(status::text)
            WHEN 'ACTIVE' THEN 0
            WHEN 'INACTIVE' THEN 1
            ELSE status::text::integer
        END;

ALTER TABLE financial
    ALTER COLUMN type_financial TYPE integer
        USING CASE upper(type_financial::text)
            WHEN 'REVENUE' THEN 0
            WHEN 'EXPENSE' THEN 1
            ELSE type_financial::text::integer
        END;

ALTER TABLE transactions
    ALTER COLUMN transaction_operation TYPE integer
        USING CASE upper(transaction_operation::text)
            WHEN 'OPEN_CASH' THEN 0
            WHEN 'CLOSE_CASH' THEN 1
            WHEN 'REVENUE' THEN 2
            WHEN 'EXPENSE' THEN 3
            ELSE transaction_operation::text::integer
        END;

ALTER TABLE user_configuration
    ALTER COLUMN theme TYPE integer
        USING CASE upper(theme::text)
            WHEN 'DARK' THEN 0
            WHEN 'LIGHT' THEN 1
            ELSE theme::text::integer
        END,
    ALTER COLUMN lang TYPE integer
        USING CASE upper(lang::text)
            WHEN 'PORTUGUESE' THEN 0
            WHEN 'ENGLISH' THEN 1
            WHEN 'SPANISH' THEN 2
            ELSE lang::text::integer
        END;
